export const ACCESS_CODE = 'ACCESS_CODE';
export const ACCESS_TOKEN = 'ACCESS_TOKEN';
export const USER_INFO = 'USER_INFO';
export const USER_UPLOAD_PHOTOS_LIST = 'USER_UPLOAD_PHOTOS_LIST';
export const USER_FOLLOWER_LIST = 'USER_FOLLOWER_LIST';
export const USER_FOLLOWING_LIST = 'USER_FOLLOWING_LIST';
export const USER_COLLECTION_LIST = 'USER_COLLECTION_LIST';
